apiVersion: v1
kind: Service
metadata:
  name: fast-api-app-service
spec:
  selector:
    app: fast-api-app
  ports:
    - port: 8000
      targetPort: 8000
      name: http
    - port: 8001
      targetPort: 8001
      name: websocket
  type: ClusterIP
