{{- if and .Values.ingress.enabled .Values.ingress.tls.enabled .Values.ingress.tls.certificate.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.ingress.tls.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "splattop.labels" . | nindent 4 }}
spec:
  secretName: {{ .Values.ingress.tls.secretName }}
  issuerRef:
    name: {{ .Values.ingress.tls.certificate.issuerName }}
    kind: {{ .Values.ingress.tls.certificate.issuerKind }}
  commonName: {{ .Values.ingress.tls.certificate.commonName }}
  dnsNames:
    {{- range .Values.ingress.tls.certificate.dnsNames }}
    - {{ . }}
    {{- end }}
{{- end }}
