{{- if .Values.databaseSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "splattop.databaseSecretName" . }}
  labels:
    {{- include "splattop.labels" . | nindent 4 }}
type: {{ default "Opaque" .Values.databaseSecret.type }}
{{- $secretData := .Values.databaseSecret.stringData }}
{{- if $secretData }}
stringData:
  {{- range $key, $value := $secretData }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- else }}
stringData: {}
{{- end }}
{{- end }}
