{{- if .Values.fastapi.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "splattop.fullname" . }}-fastapi
  labels:
    {{- include "splattop.componentLabels" (dict "component" "fastapi" "root" .) | nindent 4 }}
spec:
  type: {{ .Values.fastapi.service.type }}
  ports:
    - port: {{ .Values.fastapi.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.fastapi.service.websocketPort }}
      targetPort: websocket
      protocol: TCP
      name: websocket
  selector:
    {{- include "splattop.componentSelectorLabels" (dict "component" "fastapi" "root" .) | nindent 4 }}
{{- end }}
