{{- if and .Values.monitoring.grafana.enabled .Values.monitoring.grafana.adminCredentials.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.monitoring.grafana.adminCredentialsSecret }}
  namespace: {{ include "splattop.monitoringNamespace" . }}
  labels:
    {{- include "splattop.componentLabels" (dict "component" "grafana-admin-credentials" "root" .) | nindent 4 }}
type: Opaque
stringData:
  admin-user: {{ .Values.monitoring.grafana.adminCredentials.username | quote }}
  admin-password: {{ .Values.monitoring.grafana.adminCredentials.password | quote }}
{{- end }}
