{{- if and .Values.monitoring.prometheus.enabled .Values.monitoring.cilium.prometheusEgressKubeAPI.enabled }}
{{- $root := . -}}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: prometheus-egress-kube-apiserver
  namespace: {{ include "splattop.monitoringNamespace" . }}
  labels:
    {{- include "splattop.componentLabels" (dict "component" "monitoring-cnp-prometheus-egress" "root" $root) | nindent 4 }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/component: prometheus
  egress:
    - toEntities:
        - kube-apiserver
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
{{- end }}
