{{- if and .Values.monitoring.alertmanager.enabled .Values.monitoring.alertmanager.config.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.monitoring.alertmanager.configSecret }}
  namespace: {{ include "splattop.monitoringNamespace" . }}
  labels:
    {{- include "splattop.componentLabels" (dict "component" "alertmanager-config" "root" .) | nindent 4 }}
type: Opaque
stringData:
  alertmanager.yaml: |
{{ .Values.monitoring.alertmanager.config.content | indent 4 }}
{{- end }}
