{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "splattop.fullname" . }}-redis
  labels:
    {{- include "splattop.componentLabels" (dict "component" "redis" "root" .) | nindent 4 }}
spec:
  replicas: {{ .Values.redis.replicas }}
  selector:
    matchLabels:
      {{- include "splattop.componentSelectorLabels" (dict "component" "redis" "root" .) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "splattop.componentSelectorLabels" (dict "component" "redis" "root" .) | nindent 8 }}
    spec:
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          {{- if .Values.redis.resources }}
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
          {{- end }}
{{- end }}
